
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface A4_104404788_Symbol {
  /* terminals */
  public static final int INLINECOMMENTS = 32;
  public static final int EEOPR = 18;
  public static final int ELSE = 13;
  public static final int PLUS = 8;
  public static final int INT = 4;
  public static final int EQUAL = 26;
  public static final int QUOTES = 30;
  public static final int SEMI = 20;
  public static final int RBRA = 25;
  public static final int MULTI = 11;
  public static final int RETURN = 5;
  public static final int GEOPR = 16;
  public static final int SWITCH = 9;
  public static final int LBRA = 24;
  public static final int LEOPR = 17;
  public static final int IF = 12;
  public static final int PRINTF = 27;
  public static final int COMMENTS = 31;
  public static final int ID = 29;
  public static final int HASH = 28;
  public static final int LOPR = 15;
  public static final int COMMA = 21;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int NEOPR = 19;
  public static final int MAIN = 6;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int GOPR = 14;
  public static final int RPAR = 23;
  public static final int FOR = 7;
  public static final int VOID = 3;
  public static final int LPAR = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "VOID",
  "INT",
  "RETURN",
  "MAIN",
  "FOR",
  "PLUS",
  "SWITCH",
  "MINUS",
  "MULTI",
  "IF",
  "ELSE",
  "GOPR",
  "LOPR",
  "GEOPR",
  "LEOPR",
  "EEOPR",
  "NEOPR",
  "SEMI",
  "COMMA",
  "LPAR",
  "RPAR",
  "LBRA",
  "RBRA",
  "EQUAL",
  "PRINTF",
  "HASH",
  "ID",
  "QUOTES",
  "COMMENTS",
  "INLINECOMMENTS"
  };
}

